### ISSUE TITLE
Selecting "The Void" in the biome select causes integrated server to crash

### ISSUE THREAD

**Issue by WithLithum** [BlueStaggo/moderner-beta#25]
### Specification

- Minecraft: 1.21.3
- Fabric Loader: 0.16.9
- Fabric API: 0.110.0+1.21.3
- OS: Manjaro Linux (stable)

### Expected behaviour

[The Void](https://minecraft.wiki/w/The_Void) biome is selectable, and selects "The Void" or otherwise doesn't crash the server.

### Actual behaviour

Selecting "The Void" in the biome selection menu causes the biome selection to become "None" and creating the world with that selection freezes the game due to integrated server crashing, with the first also the most relevant exception being:

```java

java.lang.IllegalStateException: Missing element ResourceKey[minecraft:worldgen/biome / minecraft:]
	at knot/net.minecraft.class_7871.method_46748(class_7871.java:15) ~[client-intermediary.jar:?]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at knot/net.minecraft.class_7871.method_46747(class_7871.java:15) ~[client-intermediary.jar:?]
	at knot/mod.bluestaggo.modernerbeta.world.biome.provider.BiomeProviderSingle.getBiomes(BiomeProviderSingle.java:30) ~[moderner-beta-2.1.1+1.21.2-fabric.jar:?]
	at knot/mod.bluestaggo.modernerbeta.world.biome.ModernBetaBiomeSource.method_49494(ModernBetaBiomeSource.java:267) ~[moderner-beta-2.1.1+1.21.2-fabric.jar:?]
	at knot/net.minecraft.class_1966.method_49495(class_1966.java:32) ~[client-intermediary.jar:?]
	at knot/com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181) ~[guava-32.1.2-jre.jar:?]
	at knot/net.minecraft.class_1966.redirect$zhh000$fabric-biome-api-v1$getBiomes(class_1966.java:534) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1966.method_28443(class_1966.java:42) ~[client-intermediary.jar:?]
	at knot/mod.bluestaggo.modernerbeta.api.world.chunk.surface.SurfaceBuilder.initMap(SurfaceBuilder.java:24) ~[moderner-beta-2.1.1+1.21.2-fabric.jar:?]
	at knot/mod.bluestaggo.modernerbeta.api.world.chunk.surface.SurfaceBuilder.<init>(SurfaceBuilder.java:16) ~[moderner-beta-2.1.1+1.21.2-fabric.jar:?]
	at knot/mod.bluestaggo.modernerbeta.api.world.chunk.ChunkProvider.<init>(ChunkProvider.java:84) ~[moderner-beta-2.1.1+1.21.2-fabric.jar:?]
	at knot/mod.bluestaggo.modernerbeta.world.chunk.provider.ChunkProviderInfdev227.<init>(ChunkProviderInfdev227.java:60) ~[moderner-beta-2.1.1+1.21.2-fabric.jar:?]
	at knot/mod.bluestaggo.modernerbeta.world.chunk.ModernBetaChunkGenerator.initProvider(ModernBetaChunkGenerator.java:86) ~[moderner-beta-2.1.1+1.21.2-fabric.jar:?]
	at knot/mod.bluestaggo.modernerbeta.world.ModernBetaWorldInitializer.lambda$init$0(ModernBetaWorldInitializer.java:24) ~[moderner-beta-2.1.1+1.21.2-fabric.jar:?]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at knot/com.google.common.collect.Maps$IteratorBasedAbstractMap.forEachEntry(Maps.java:3868) ~[guava-32.1.2-jre.jar:?]
	at knot/com.google.common.collect.Maps$IteratorBasedAbstractMap$1.forEach(Maps.java:3862) ~[guava-32.1.2-jre.jar:?]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116) ~[?:?]
	at knot/mod.bluestaggo.modernerbeta.world.ModernBetaWorldInitializer.init(ModernBetaWorldInitializer.java:17) ~[moderner-beta-2.1.1+1.21.2-fabric.jar:?]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
	at knot/dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:54) ~[architectury-14.0.4-fabric.jar:?]
	at knot/dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:63) ~[architectury-14.0.4-fabric.jar:?]
	at knot/com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-32.1.2-jre.jar:?]
	at knot/jdk.proxy2/jdk.proxy2.$Proxy77.stateChanged(Unknown Source) ~[?:?]
	at knot/dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$9(EventHandlerImpl.java:66) ~[architectury-14.0.4-fabric.jar:?]
	at knot/net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:38) ~[fabric-lifecycle-events-v1-2.5.1+6da5ef6940-d80a34a6642d1777.jar:?]
	at knot/net.minecraft.server.MinecraftServer.handler$zmf000$fabric-lifecycle-events-v1$beforeSetupServer(MinecraftServer.java:2699) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:678) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

### Additional information

- [crash-2024-12-02_15.24.23-server.txt](https://github.com/user-attachments/files/17974242/crash-2024-12-02_15.24.23-server.txt)

**Comment by forkiesassds** [comment]
This should be fixed in the next update.
